package hello.my_self.mock;

import hello.my_self.mystack.domain.MyStack;
import hello.my_self.mystack.repository.MyStackRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

public class FakeMyStackRepository implements MyStackRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<MyStack> data = new ArrayList<>();

}
