package hello.my_self.mock;

import hello.my_self.myproject.domain.MyProject;
import hello.my_self.myreward.domain.MyReward;
import hello.my_self.myreward.repository.MyRewardRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

public class FakeMyRewardRepository implements MyRewardRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<MyReward> data = new ArrayList<>();


    @Override
    public MyReward save(MyReward myReward) {
        MyReward reward = MyReward.builder()
                .id(autoGeneratedId.incrementAndGet())
                .name(myReward.getName())
                .host(myReward.getHost())
                .description(myReward.getDescription())
                .number(myReward.getNumber())
                .member(myReward.getMember())
                .build();

        data.add(reward);
        return reward;
    }
}
