package hello.my_self.mock;

import hello.my_self.member.domain.Member;
import hello.my_self.member.repository.MemberRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

public class FakeMemberRepository implements MemberRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Member> data = new ArrayList<>();

    @Override
    public Member save(Member member) {
        if (member.getId() == null || member.getId() == 0){
            Member newMember = Member.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .name(member.getName())
                    .age(member.getAge())
                    .birth(member.getBirth())
                    .sex(member.getSex())
                    .description(member.getDescription())
                    .build();

            return newMember;
        }
        return null;
    }
}
